'use strict'

const actions = {
  ADD_DAY: 'ADD_DAY',
  REMOVE_DAY: 'REMOVE_DAY',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  ADD_HOTEL: 'ADD_HOTEL',
  REMOVE_HOTEL: 'REMOVE_HOTEL',
  LOAD_DESTINATIONS: 'LOAD_DESTINATIONS',
  ADD_DESTINATION: 'ADD_DESTINATION',
  SET_DESTINATION: 'SET_DESTINATION',
  REMOVE_DESTINATION: 'REMOVE_DESTINATION',
  ADD_RESTAURANT: 'ADD_RESTAURANT',
  REMOVE_RESTAURANT: 'REMOVE_RESTAURANT',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  SET_BACKGROUND_IMAGE: 'SET_BACKGROUND_IMAGE'
}

export default actions