'use strict'

const actions = {
  SET_USER: 'SET_USER',
  ADD_DAY: 'ADD_DAY',
  REMOVE_DAY: 'REMOVE_DAY',
  ADD_HOTEL: 'ADD_HOTEL',
  SET_HOTELS: 'SET_HOTELS',
  REMOVE_HOTEL: 'REMOVE_HOTEL',
  LOAD_DESTINATIONS: 'LOAD_DESTINATIONS',
  ADD_DESTINATION: 'ADD_DESTINATION',
  SET_DESTINATION: 'SET_DESTINATION',
  REMOVE_DESTINATION: 'REMOVE_DESTINATION',
  ADD_RESTAURANT: 'ADD_RESTAURANT',
  SET_RESTAURANTS: 'SET_RESTAURANTS',
  REMOVE_RESTAURANT: 'REMOVE_RESTAURANT',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  SET_ACTIVITIES: 'SET_ACTIVITIES',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  SET_BACKGROUND_IMAGE: 'SET_BACKGROUND_IMAGE'
}

export default actions